### ISSUE TITLE
Does this work for personal messages, or page messages only?

### ISSUE THREAD

**Issue by mahir-e** [aryan1234/facebook_messages#1]
I tried running the code, but the `GET` request returns the following error:

```
 error: 
   { message: 'Unsupported get request. Object with ID \'my_conversation_id\' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api',
```

I selected the read_mailbox_permissions option when I generated my user token, so I'm wondering if accessing the inbox is just possible for apps and pages, or if it's still possible to access my personal inbox?

**Comment by aryan1234** [comment]
Yes this works for personal messages
Steps
1) open 
https://developers.facebook.com/tools/explorer/?method=GET&path=me%3Ffields%3Dinbox&version=v2.3
2)click on submit
3)select conversation id of chat thread you want

**Comment by aryankanwar** [comment]
Yes this works for personal messages
// go to https://developers.facebook.com/tools/explorer/?method=GET&path=me%3Ffields%3Dinbox&version=v2.3
//1)click on Get token
//2) select Get user acess token 
//3)Tick read_mailbox permission 
//Fianlly click on get access token
//click on submit
//select conversation id of chat thread you want to see messages
// using v2.3 because new versions dont have permission for reading inbox

**Comment by mahir-e** [comment]
I followed the instructions above, but when I click submit, I get this error

<img width="853" alt="screen shot 2017-06-04 at 12 18 10 am" src="https://cloud.githubusercontent.com/assets/1160318/26759727/7eed7432-48bb-11e7-8fc4-1c33197ce3d2.png">

However, I am able to access `me/inbox?fields=message` which returns data in the form of 
```
"data": [
    {
      "id": "7.............9",
      "updated_time": "2017-06-04T06:03:19+0000"
    },
```

I used this as the conversation id, but when I run the code, the error message is the same as the one in the explorer output:

```
{ error: 
   { message: '(#298) You must be a developer of the application',
     type: 'OAuthException',
     code: 298,
     fbtrace_id: 'HxStVTxJ75v' } }
```

**Comment by mahir-e** [comment]
As an update, when I associated the token with one of my facebook applications, it seems to grant the necessary permissions.

However, I'm also seeing another issue:

While the app works fine for conversation_ids with 15-16 characters, it's not working with conversation_ids of 17 characters.  From what I've observed, these conversations started more recently than ones with 15-16 characters.   

With the recent conversation_ids, the response does not contain a `comments` key.

**Comment by aryan1234** [comment]
How did you associate the token with one of facebook apllications?Can you read the messsages?
The conversation id length had no issue earlier.

**Comment by aryankanwar** [comment]
Versions above than 2.2 require special reviewing from Facebook team to access the Messages

![18947294_1941710912711229_1027467920_o](https://cloud.githubusercontent.com/assets/13161592/26783491/17e3b6be-4a16-11e7-8835-ff0695db5b97.jpg)

**Comment by fewella** [comment]
After following all the instructions, I have the conversation ids I need, but I'm getting the same error message as Mahir did ("Unsupported get request. Object with ID \'3...........9\' does not exist, cannot be loaded due to missing permissions, or does not support this operation."). 

I've already made sure my access token has read-mailbox permissions. Was this issue ever resolved?

**Comment by aryankanwar** [comment]
This code is outdated now as Facebook has deprecated the 2.2v of Graph API. Versions above that require special reviewing from Facebook team to access the Messages.
